create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  preco numeric(10,2) not null default 0,
  "precoOriginal" numeric(10,2),
  "estaEmPromocao" boolean not null default false,
  "textoDestaquePromo" text default '',
  cronometro text,
  categoria text,
  genero text,
  imagem text default '',
  fotos jsonb not null default '[]'::jsonb,
  cores jsonb not null default '[]'::jsonb,
  tamanhos jsonb not null default '[]'::jsonb,
  descricao text default '',
  estoque integer not null default 0,
  relevancia integer not null default 0,
  data date,
  data_cadastro timestamptz not null default now()
);

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('carrossel', 'grelha', 'intermediario')),
  ordem integer not null default 0,
  etiqueta text default '',
  titulo text default '',
  texto text default '',
  botao text default '',
  link text default '',
  imagem text default '',
  "imagemMobile" text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.admin_sessoes (
  token_hash text primary key,
  email text not null,
  expira_em timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null unique,
  cpf text default '',
  telefone text default '',
  senha text not null,
  endereco jsonb not null default '{}'::jsonb,
  foto text default '',
  whatsapp_ok boolean not null default false,
  aceitou_termos boolean not null default false,
  data_cadastro date not null default current_date
);

create table if not exists public.cupons (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  tipo text not null default 'porcentagem',
  valor numeric(10,2) not null default 0,
  "limiteUso" integer not null default 0,
  usos integer not null default 0,
  validade timestamptz,
  ativo boolean not null default true
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  data timestamptz not null default now(),
  cliente jsonb not null default '{}'::jsonb,
  endereco jsonb not null default '{}'::jsonb,
  itens jsonb not null default '[]'::jsonb,
  cupom jsonb,
  metodo text default 'pix',
  status text not null default 'Aguardando Pagamento',
  total numeric(10,2) not null default 0,
  frete_modalidade text,
  frete_codigo text,
  frete_valor numeric(10,2) default 0,
  frete_prazo text,
  frete_origem text,
  frete_detalhes jsonb,
  codigo_rastreamento text,
  url_rastreamento text,
  data_envio timestamptz,
  data_entrega timestamptz,
  bling_id text,
  bling_order_id text,
  bling_status text,
  bling_tracking text,
  data_bling_sync timestamptz,
  upseller_id text,
  upseller_tracking text,
  upseller_status text,
  data_upseller_sync timestamptz
);

alter table public.produtos enable row level security;
alter table public.banners enable row level security;
alter table public.admin_sessoes enable row level security;
alter table public.clientes enable row level security;
alter table public.cupons enable row level security;
alter table public.pedidos enable row level security;

drop policy if exists "produtos_public_select" on public.produtos;
drop policy if exists "banners_public_select" on public.banners;
drop policy if exists "cupons_public_select" on public.cupons;

create policy "produtos_public_select" on public.produtos
  for select to anon, authenticated using (true);

create policy "banners_public_select" on public.banners
  for select to anon, authenticated using (true);

create policy "cupons_public_select" on public.cupons
  for select to anon, authenticated using (true);

insert into storage.buckets (id, name, "public")
values ('images', 'images', true)
on conflict (id) do update set "public" = excluded."public";

alter table storage.objects enable row level security;

drop policy if exists "images_public_read" on storage.objects;

create policy "images_public_read" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'images');
