create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  preco numeric(10,2) not null default 0,
  "precoOriginal" numeric(10,2),
  "estaEmPromocao" boolean not null default false,
  "textoDestaquePromo" text default '',
  cronometro text,
  categoria text,
  genero text,
  imagem text default '',
  fotos jsonb not null default '[]'::jsonb,
  cores jsonb not null default '[]'::jsonb,
  tamanhos jsonb not null default '[]'::jsonb,
  descricao text default '',
  estoque integer not null default 0,
  relevancia integer not null default 0,
  data date,
  data_cadastro timestamptz not null default now()
);

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('carrossel', 'grelha', 'intermediario')),
  ordem integer not null default 0,
  etiqueta text default '',
  titulo text default '',
  texto text default '',
  botao text default '',
  link text default '',
  imagem text default '',
  "imagemMobile" text default '',
  created_at timestamptz not null default now()
);

alter table public.produtos enable row level security;
alter table public.banners enable row level security;

drop policy if exists "produtos_public_select" on public.produtos;
drop policy if exists "produtos_admin_insert" on public.produtos;
drop policy if exists "produtos_admin_update" on public.produtos;
drop policy if exists "produtos_admin_delete" on public.produtos;
drop policy if exists "banners_public_select" on public.banners;
drop policy if exists "banners_admin_insert" on public.banners;
drop policy if exists "banners_admin_update" on public.banners;
drop policy if exists "banners_admin_delete" on public.banners;

create policy "produtos_public_select" on public.produtos
  for select to anon, authenticated using (true);
create policy "produtos_admin_insert" on public.produtos
  for insert to anon, authenticated with check (true);
create policy "produtos_admin_update" on public.produtos
  for update to anon, authenticated using (true) with check (true);
create policy "produtos_admin_delete" on public.produtos
  for delete to anon, authenticated using (true);

create policy "banners_public_select" on public.banners
  for select to anon, authenticated using (true);
create policy "banners_admin_insert" on public.banners
  for insert to anon, authenticated with check (true);
create policy "banners_admin_update" on public.banners
  for update to anon, authenticated using (true) with check (true);
create policy "banners_admin_delete" on public.banners
  for delete to anon, authenticated using (true);

insert into storage.buckets (id, name, "public")
values ('images', 'images', true)
on conflict (id) do update set "public" = excluded."public";

alter table storage.objects enable row level security;

drop policy if exists "images_public_read" on storage.objects;
drop policy if exists "images_public_insert" on storage.objects;

create policy "images_public_read" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'images');

create policy "images_public_insert" on storage.objects
  for insert to anon, authenticated
  with check (bucket_id = 'images');